import type { MasterConfig, UserRole } from "@/types";

export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "SkyMap LIMS";

export const COLLECTIONS = {
  users: "users",
  roles: "roles",
  departments: "departments",
  laboratories: "laboratories",
  products: "products",
  customers: "customers",
  materials: "materials",
  sampleTypes: "sampleTypes",
  samples: "samples",
  tests: "tests",
  testMasters: "testMasters",
  methods: "methods",
  specifications: "specifications",
  instruments: "instruments",
  units: "units",
  storageConditions: "storageConditions",
  reports: "reports",
  activities: "activities",
  auditTrail: "auditTrail",
  notifications: "notifications",
  counters: "counters",
} as const;

export const ROLE_LABELS: Record<UserRole, string> = {
  admin: "Administrator",
  qa: "QA",
  qc: "QC",
  reviewer: "Reviewer",
  analyst: "Analyst",
  viewer: "Viewer",
};

export const ROLE_PERMISSIONS: Record<
  UserRole,
  {
    manageUsers: boolean;
    manageMasters: boolean;
    manageSamples: boolean;
    recordResults: boolean;
    review: boolean;
    approve: boolean;
    release: boolean;
    viewReports: boolean;
    export: boolean;
  }
> = {
  admin: {
    manageUsers: true,
    manageMasters: true,
    manageSamples: true,
    recordResults: true,
    review: true,
    approve: true,
    release: true,
    viewReports: true,
    export: true,
  },
  qa: {
    manageUsers: false,
    manageMasters: true,
    manageSamples: true,
    recordResults: false,
    review: true,
    approve: true,
    release: true,
    viewReports: true,
    export: true,
  },
  qc: {
    manageUsers: false,
    manageMasters: false,
    manageSamples: true,
    recordResults: true,
    review: true,
    approve: false,
    release: false,
    viewReports: true,
    export: true,
  },
  reviewer: {
    manageUsers: false,
    manageMasters: false,
    manageSamples: true,
    recordResults: false,
    review: true,
    approve: false,
    release: false,
    viewReports: true,
    export: true,
  },
  analyst: {
    manageUsers: false,
    manageMasters: false,
    manageSamples: true,
    recordResults: true,
    review: false,
    approve: false,
    release: false,
    viewReports: true,
    export: false,
  },
  viewer: {
    manageUsers: false,
    manageMasters: false,
    manageSamples: false,
    recordResults: false,
    review: false,
    approve: false,
    release: false,
    viewReports: true,
    export: false,
  },
};

export const SAMPLE_STATUS_LABELS = {
  received: "Received",
  pending: "Pending",
  in_testing: "In Testing",
  in_review: "In Review",
  approved: "Approved",
  rejected: "Rejected",
  cancelled: "Cancelled",
  released: "Released",
} as const;

export const PRIORITY_LABELS = {
  low: "Low",
  normal: "Normal",
  high: "High",
  urgent: "Urgent",
} as const;

export const INSTRUMENT_STATUS_LABELS = {
  available: "Available",
  in_use: "In Use",
  maintenance: "Maintenance",
  retired: "Retired",
} as const;

export const PAGE_SIZE = 10;

export const MASTER_CONFIGS: Record<string, MasterConfig> = {
  departments: {
    collection: COLLECTIONS.departments,
    title: "Department Master",
    singular: "Department",
    description: "Manage laboratory departments and organizational units.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. QC, QA, MICRO",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Quality Control Department",
      },
      {
        key: "head",
        label: "Department Head",
        type: "text",
        placeholder: "Name of department head",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Scope, responsibilities, or notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "head", label: "Head" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  laboratories: {
    collection: COLLECTIONS.laboratories,
    title: "Laboratory Master",
    singular: "Laboratory",
    description: "Configure laboratories, locations, departments, and accreditation details.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. LAB-MICRO, LAB-QC",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Microbiology Laboratory",
      },
      {
        key: "departmentId",
        label: "Department",
        type: "select",
        referenceCollection: COLLECTIONS.departments,
        referenceLabelKey: "name",
      },
      {
        key: "location",
        label: "Location",
        type: "text",
        placeholder: "Building, floor, or site",
      },
      {
        key: "accreditation",
        label: "Accreditation",
        type: "text",
        placeholder: "e.g. ISO 17025, NABL",
      },
      {
        key: "contactEmail",
        label: "Contact Email",
        type: "email",
        placeholder: "lab.contact@company.com",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Scope, instruments, or operational notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "departmentName", label: "Department" },
      { key: "location", label: "Location" },
      { key: "accreditation", label: "Accreditation" },
      { key: "contactEmail", label: "Contact" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  products: {
    collection: COLLECTIONS.products,
    title: "Product Master",
    singular: "Product",
    description: "Maintain pharmaceutical products, formulations, and customer links.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. PRD-001, PARA-500",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Paracetamol Tablets 500 mg",
      },
      {
        key: "customerId",
        label: "Customer / Sponsor",
        type: "select",
        referenceCollection: COLLECTIONS.customers,
        referenceLabelKey: "name",
      },
      {
        key: "dosageForm",
        label: "Dosage Form",
        type: "select",
        options: [
          { label: "Tablet", value: "Tablet" },
          { label: "Capsule", value: "Capsule" },
          { label: "Injection", value: "Injection" },
          { label: "Syrup", value: "Syrup" },
          { label: "Suspension", value: "Suspension" },
          { label: "Cream", value: "Cream" },
          { label: "Ointment", value: "Ointment" },
          { label: "Powder", value: "Powder" },
          { label: "Solution", value: "Solution" },
          { label: "Drops", value: "Drops" },
        ],
      },
      {
        key: "strength",
        label: "Strength",
        type: "text",
        placeholder: "e.g. 500 mg, 10 mg/5 ml",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Composition, pack size, or storage notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "customerName", label: "Customer" },
      { key: "dosageForm", label: "Dosage Form" },
      { key: "strength", label: "Strength" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  customers: {
    collection: COLLECTIONS.customers,
    title: "Customer Master",
    singular: "Customer",
    description: "Manage customers, sponsors, and sample submitters.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. CUST-001, SPONSOR-ABC",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Acme Pharmaceuticals Pvt. Ltd.",
      },
      {
        key: "contactPerson",
        label: "Contact Person",
        type: "text",
        placeholder: "Primary contact name",
      },
      {
        key: "email",
        label: "Email",
        type: "email",
        placeholder: "contact@customer.com",
      },
      {
        key: "phone",
        label: "Phone",
        type: "phone",
        placeholder: "+91 98765 43210",
      },
      {
        key: "address",
        label: "Address",
        type: "textarea",
        placeholder: "Street, city, state, postal code",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "contactPerson", label: "Contact" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "address", label: "Address" },
      { key: "isActive", label: "Status" },
    ],
  },
  materials: {
    collection: COLLECTIONS.materials,
    title: "Material Master",
    singular: "Material",
    description: "Track raw materials, reagents, and reference standards.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. RM-001, REAG-NACL",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Sodium Chloride, USP",
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: [
          { label: "Raw Material", value: "Raw Material" },
          { label: "API", value: "API" },
          { label: "Excipient", value: "Excipient" },
          { label: "Reagent", value: "Reagent" },
          { label: "Reference Standard", value: "Reference Standard" },
          { label: "Solvent", value: "Solvent" },
          { label: "Consumable", value: "Consumable" },
          { label: "Buffer", value: "Buffer" },
          { label: "Culture Media", value: "Culture Media" },
        ],
      },
      {
        key: "casNumber",
        label: "CAS Number",
        type: "text",
        placeholder: "e.g. 7732-18-5",
      },
      {
        key: "supplier",
        label: "Supplier",
        type: "text",
        placeholder: "Preferred vendor or manufacturer",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Grade, storage, or handling notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "casNumber", label: "CAS" },
      { key: "supplier", label: "Supplier" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  "sample-types": {
    collection: COLLECTIONS.sampleTypes,
    title: "Sample Type Master",
    singular: "Sample Type",
    description: "Define sample categories and retention periods used during sample registration.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. FP, RM, IP, STAB",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Finished Product, Raw Material",
      },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          { label: "Finished Product", value: "Finished Product" },
          { label: "Raw Material", value: "Raw Material" },
          { label: "In-Process", value: "In-Process" },
          { label: "Stability", value: "Stability" },
          { label: "Packaging", value: "Packaging" },
          { label: "Environmental", value: "Environmental" },
          { label: "Other", value: "Other" },
        ],
      },
      {
        key: "retentionDays",
        label: "Retention Days",
        type: "number",
        placeholder: "e.g. 365",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Handling, retention, or registration notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "retentionDays", label: "Retention Days" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  "storage-conditions": {
    collection: COLLECTIONS.storageConditions,
    title: "Storage Condition Master",
    singular: "Storage Condition",
    description: "Maintain temperature, humidity, and storage requirement profiles.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. AMB, REF-2-8, FRZ-20",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Ambient, Refrigerated 2–8 °C",
      },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          { label: "Ambient", value: "Ambient" },
          { label: "Controlled Room Temperature", value: "CRT" },
          { label: "Refrigerated", value: "Refrigerated" },
          { label: "Frozen", value: "Frozen" },
          { label: "Deep Freeze", value: "Deep Freeze" },
          { label: "Protect from Light", value: "Protect from Light" },
          { label: "Other", value: "Other" },
        ],
      },
      {
        key: "temperature",
        label: "Temperature",
        type: "text",
        placeholder: "e.g. 15–25 °C, 2–8 °C, ≤ −20 °C",
      },
      {
        key: "humidity",
        label: "Humidity",
        type: "text",
        placeholder: "e.g. ≤ 60% RH, 35–65% RH",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Handling, light protection, or location notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "temperature", label: "Temperature" },
      { key: "humidity", label: "Humidity" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  units: {
    collection: COLLECTIONS.units,
    title: "Unit Master",
    singular: "Unit",
    description: "Units of measure used across tests, parameters, and specifications.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. U-MG, U-PCT, U-PH",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Milligram, Percent, pH Unit",
      },
      {
        key: "symbol",
        label: "Symbol",
        type: "text",
        required: true,
        placeholder: "e.g. mg, %, mL, °C",
      },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          { label: "Mass", value: "Mass" },
          { label: "Volume", value: "Volume" },
          { label: "Concentration", value: "Concentration" },
          { label: "Length", value: "Length" },
          { label: "Temperature", value: "Temperature" },
          { label: "Time", value: "Time" },
          { label: "Pressure", value: "Pressure" },
          { label: "Count / Quantity", value: "Count" },
          { label: "Other", value: "Other" },
        ],
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Usage notes or conversion context",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "symbol", label: "Symbol" },
      { key: "category", label: "Category" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  methods: {
    collection: COLLECTIONS.methods,
    title: "Method Master",
    singular: "Method",
    description: "Analytical methods, versions, and SOP references.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. METH-HPLC-01, SOP-QC-ASS",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Assay by HPLC, Karl Fischer Titration",
      },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          { label: "Chromatography", value: "Chromatography" },
          { label: "Spectroscopy", value: "Spectroscopy" },
          { label: "Titration", value: "Titration" },
          { label: "Physical", value: "Physical" },
          { label: "Microbiological", value: "Microbiological" },
          { label: "Wet Chemistry", value: "Wet Chemistry" },
          { label: "Other", value: "Other" },
        ],
      },
      {
        key: "version",
        label: "Version",
        type: "text",
        placeholder: "e.g. 1.0, Rev B",
      },
      {
        key: "sopReference",
        label: "SOP Reference",
        type: "text",
        placeholder: "e.g. SOP-QC-001",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Principle, scope, or procedure notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "version", label: "Version" },
      { key: "sopReference", label: "SOP" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  instruments: {
    collection: COLLECTIONS.instruments,
    title: "Instrument Master",
    singular: "Instrument",
    description: "Laboratory instruments, calibration schedules, and availability.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. HPLC-01, BAL-001",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "HPLC System, Analytical Balance",
      },
      {
        key: "laboratoryId",
        label: "Laboratory",
        type: "select",
        referenceCollection: COLLECTIONS.laboratories,
        referenceLabelKey: "name",
      },
      {
        key: "manufacturer",
        label: "Manufacturer",
        type: "text",
        placeholder: "e.g. Agilent, Shimadzu, Mettler Toledo",
      },
      {
        key: "model",
        label: "Model",
        type: "text",
        placeholder: "Model number or series",
      },
      {
        key: "serialNumber",
        label: "Serial Number",
        type: "text",
        placeholder: "Manufacturer serial number",
      },
      {
        key: "calibrationDue",
        label: "Calibration Due",
        type: "date",
      },
      {
        key: "status",
        label: "Operational Status",
        type: "select",
        options: [
          { label: "Available", value: "available" },
          { label: "In Use", value: "in_use" },
          { label: "Maintenance", value: "maintenance" },
          { label: "Retired", value: "retired" },
        ],
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "laboratoryName", label: "Laboratory" },
      { key: "manufacturer", label: "Manufacturer" },
      { key: "model", label: "Model" },
      { key: "serialNumber", label: "Serial No." },
      { key: "calibrationDue", label: "Calibration Due" },
      { key: "status", label: "Status" },
      { key: "isActive", label: "Record" },
    ],
  },
  specifications: {
    collection: COLLECTIONS.specifications,
    title: "Specification Master",
    singular: "Specification",
    description: "Product specifications, versions, and linked analytical tests.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. SPEC-PARA-500, FP-ASS-01",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Paracetamol Tablets 500 mg Specification",
      },
      {
        key: "productId",
        label: "Product",
        type: "select",
        referenceCollection: COLLECTIONS.products,
        referenceLabelKey: "name",
      },
      {
        key: "version",
        label: "Version",
        type: "text",
        placeholder: "e.g. 1.0, Rev A",
      },
      {
        key: "effectiveDate",
        label: "Effective Date",
        type: "date",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Scope, pharmacopoeia reference, or acceptance notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "productName", label: "Product" },
      { key: "version", label: "Version" },
      { key: "effectiveDate", label: "Effective Date" },
      { key: "testCount", label: "Tests" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
  "test-masters": {
    collection: COLLECTIONS.testMasters,
    title: "Test Master",
    singular: "Test",
    description: "Define analytical tests, linked methods, and result parameters.",
    fields: [
      {
        key: "code",
        label: "Code",
        type: "text",
        required: true,
        placeholder: "e.g. ASSAY-HPLC, MOIST-KF",
      },
      {
        key: "name",
        label: "Name",
        type: "text",
        required: true,
        searchable: true,
        placeholder: "Assay by HPLC, Loss on Drying",
      },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          { label: "Physical", value: "Physical" },
          { label: "Chemical", value: "Chemical" },
          { label: "Microbiological", value: "Microbiological" },
          { label: "Stability", value: "Stability" },
          { label: "Environmental", value: "Environmental" },
          { label: "Identification", value: "Identification" },
          { label: "Other", value: "Other" },
        ],
      },
      {
        key: "methodId",
        label: "Method",
        type: "select",
        referenceCollection: COLLECTIONS.methods,
        referenceLabelKey: "name",
      },
      {
        key: "instrumentId",
        label: "Instrument",
        type: "select",
        referenceCollection: COLLECTIONS.instruments,
        referenceLabelKey: "name",
      },
      {
        key: "estimatedHours",
        label: "Estimated Hours",
        type: "number",
        placeholder: "e.g. 4",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Scope, sample prep, or acceptance notes",
      },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "methodName", label: "Method" },
      { key: "instrumentName", label: "Instrument" },
      { key: "parameterCount", label: "Parameters" },
      { key: "estimatedHours", label: "Est. Hours" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status" },
    ],
  },
};

export const NAV_ITEMS = [
  {
    title: "Overview",
    items: [
      { title: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
      { title: "Search", href: "/search", icon: "Search" },
      { title: "Notifications", href: "/notifications", icon: "Bell" },
    ],
  },
  {
    title: "Operations",
    items: [
      { title: "Samples", href: "/samples", icon: "FlaskConical" },
      { title: "Testing", href: "/testing", icon: "TestTube2" },
      { title: "Reports", href: "/reports", icon: "FileText" },
      { title: "Approvals", href: "/approvals", icon: "CheckCircle2" },
    ],
  },
  {
    title: "Masters",
    items: [
      { title: "Departments", href: "/masters/departments", icon: "Building2" },
      { title: "Laboratories", href: "/masters/laboratories", icon: "Microscope" },
      { title: "Products", href: "/masters/products", icon: "Package" },
      { title: "Customers", href: "/masters/customers", icon: "Users" },
      { title: "Materials", href: "/masters/materials", icon: "Boxes" },
      { title: "Tests", href: "/masters/test-masters", icon: "ClipboardList" },
      { title: "Instruments", href: "/masters/instruments", icon: "Cpu" },
      { title: "Specifications", href: "/masters/specifications", icon: "BookMarked" },
      { title: "Methods", href: "/masters/methods", icon: "BookOpen" },
      { title: "Units", href: "/masters/units", icon: "Ruler" },
      { title: "Sample Types", href: "/masters/sample-types", icon: "Tags" },
      { title: "Storage", href: "/masters/storage-conditions", icon: "Thermometer" },
    ],
  },
  {
    title: "Administration",
    items: [
      { title: "Users", href: "/users", icon: "UserCog", roles: ["admin"] as UserRole[] },
      { title: "Activity Logs", href: "/activities", icon: "Activity" },
      { title: "Audit Trail", href: "/audit-trail", icon: "ShieldCheck" },
      { title: "Settings", href: "/settings", icon: "Settings" },
    ],
  },
] as const;
