"use client";

import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Download, FileText, Plus, Search } from "lucide-react";
import { useAuth } from "@/contexts/auth-context";
import { COLLECTIONS, PAGE_SIZE } from "@/lib/constants";
import {
  createDocument,
  getNextSequence,
  logActivity,
  updateDocument,
} from "@/lib/firebase/firestore";
import { exportToCsv, exportToExcel, exportToPdf } from "@/lib/export";
import { formatDateTime } from "@/lib/utils";
import {
  useCollection,
  useDebouncedValue,
  usePagination,
} from "@/hooks/use-firestore";
import { PageHeader } from "@/components/shared/page-header";
import {
  EmptyState,
  ErrorState,
  PageShell,
  TableSkeleton,
} from "@/components/shared/states";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { LabTest, Report, Sample } from "@/types";

export default function ReportsPage() {
  const { profile, hasPermission } = useAuth();
  const [refreshKey, setRefreshKey] = useState(0);
  const { data, loading, error } = useCollection<Report>(
    COLLECTIONS.reports,
    refreshKey
  );
  const { data: samples } = useCollection<Sample>(COLLECTIONS.samples);
  const { data: tests } = useCollection<LabTest>(COLLECTIONS.tests);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const debounced = useDebouncedValue(search);
  const [open, setOpen] = useState(false);
  const [reportType, setReportType] = useState<Report["type"]>("coa");
  const [sampleId, setSampleId] = useState("");
  const [testId, setTestId] = useState("");
  const [saving, setSaving] = useState(false);

  const filtered = useMemo(() => {
    const q = debounced.trim().toLowerCase();
    return data.filter((r) => {
      const matchesType = typeFilter === "all" || r.type === typeFilter;
      const matchesSearch =
        !q ||
        r.reportNumber.toLowerCase().includes(q) ||
        r.title.toLowerCase().includes(q) ||
        (r.sampleNumber || "").toLowerCase().includes(q);
      return matchesType && matchesSearch;
    });
  }, [data, debounced, typeFilter]);

  const { page, setPage, totalPages, pageItems } = usePagination(
    filtered,
    PAGE_SIZE
  );

  const generate = async () => {
    setSaving(true);
    try {
      const sample = samples.find((s) => s.id === sampleId);
      const test = tests.find((t) => t.id === testId);
      let reportNumber = `RPT-${Date.now()}`;
      try {
        reportNumber = await getNextSequence("reports", "RPT");
      } catch {
        // ignore
      }
      const titleMap: Record<Report["type"], string> = {
        coa: "Certificate of Analysis",
        test_report: "Test Report",
        dashboard: "Dashboard Report",
        monthly: "Monthly Report",
        analyst: "Analyst Report",
        qa: "QA Report",
        laboratory: "Laboratory Report",
      };
      const content = [
        titleMap[reportType],
        sample ? `Sample: ${sample.sampleNumber}` : "",
        test ? `Test: ${test.testNumber} (${test.testName})` : "",
        `Generated by: ${profile?.displayName}`,
        `Date: ${new Date().toLocaleString()}`,
        test
          ? `Result: ${test.resultStatus} | Workflow: ${test.status}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

      const id = await createDocument(COLLECTIONS.reports, {
        reportNumber,
        type: reportType,
        sampleId: sample?.id,
        sampleNumber: sample?.sampleNumber,
        testId: test?.id,
        title: titleMap[reportType],
        status: "pending",
        version: 1,
        content,
        generatedBy: profile?.uid,
        generatedByName: profile?.displayName,
      });
      await logActivity({
        action: "Generate Report",
        entityType: "reports",
        entityId: id,
        entityLabel: reportNumber,
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        userEmail: profile?.email,
      });
      toast.success("Report generated");
      setOpen(false);
      setRefreshKey((k) => k + 1);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to generate");
    } finally {
      setSaving(false);
    }
  };

  const approve = async (report: Report) => {
    await updateDocument(COLLECTIONS.reports, report.id, {
      status: "approved",
      approvedBy: profile?.uid,
      approvedByName: profile?.displayName,
      version: (report.version || 1) + 0,
    });
    await logActivity({
      action: "Approve Report",
      entityType: "reports",
      entityId: report.id,
      entityLabel: report.reportNumber,
      userId: profile?.uid || "",
      userName: profile?.displayName || "User",
      userEmail: profile?.email,
    });
    toast.success("Report approved");
    setRefreshKey((k) => k + 1);
  };

  const downloadReport = (report: Report) => {
    exportToPdf(
      report.title,
      [
        {
          reportNumber: report.reportNumber,
          sample: report.sampleNumber || "",
          status: report.status,
          version: report.version,
          generatedBy: report.generatedByName || "",
          content: report.content || "",
        },
      ],
      [
        { key: "reportNumber", label: "Report #" },
        { key: "sample", label: "Sample" },
        { key: "status", label: "Status" },
        { key: "version", label: "Version" },
        { key: "generatedBy", label: "Generated By" },
        { key: "content", label: "Content" },
      ],
      report.reportNumber
    );
    logActivity({
      action: "Download Report",
      entityType: "reports",
      entityId: report.id,
      entityLabel: report.reportNumber,
      userId: profile?.uid || "",
      userName: profile?.displayName || "User",
      userEmail: profile?.email,
    });
  };

  const exportRows = filtered.map((r) => ({
    reportNumber: r.reportNumber,
    title: r.title,
    type: r.type,
    sample: r.sampleNumber || "",
    status: r.status,
    version: r.version,
  }));
  const cols = [
    { key: "reportNumber", label: "Report #" },
    { key: "title", label: "Title" },
    { key: "type", label: "Type" },
    { key: "sample", label: "Sample" },
    { key: "status", label: "Status" },
    { key: "version", label: "Version" },
  ];

  return (
    <PageShell>
      <PageHeader
        title="Reports"
        description="Generate COA, test reports, and operational exports."
        breadcrumbs={[
          { label: "Dashboard", href: "/dashboard" },
          { label: "Reports" },
        ]}
        actions={
          <>
            <Button
              variant="outline"
              className="h-10 rounded-xl"
              onClick={() => exportToExcel("reports", exportRows, cols)}
            >
              <Download className="mr-2 size-4" />
              Excel
            </Button>
            <Button
              variant="outline"
              className="h-10 rounded-xl"
              onClick={() => exportToCsv("reports", exportRows, cols)}
            >
              CSV
            </Button>
            <Button className="h-10 rounded-xl" onClick={() => setOpen(true)}>
              <Plus className="mr-2 size-4" />
              Generate Report
            </Button>
          </>
        }
      />

      <div className="mb-4 flex flex-col gap-3 sm:flex-row">
        <div className="relative flex-1 sm:max-w-md">
          <Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-10 rounded-xl pl-9"
            placeholder="Search reports..."
          />
        </div>
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="h-10 w-full rounded-xl sm:w-48">
            <SelectValue placeholder="Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All types</SelectItem>
            <SelectItem value="coa">COA</SelectItem>
            <SelectItem value="test_report">Test Report</SelectItem>
            <SelectItem value="dashboard">Dashboard</SelectItem>
            <SelectItem value="monthly">Monthly</SelectItem>
            <SelectItem value="analyst">Analyst</SelectItem>
            <SelectItem value="qa">QA</SelectItem>
            <SelectItem value="laboratory">Laboratory</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {loading ? (
        <TableSkeleton />
      ) : error ? (
        <ErrorState description={error} onRetry={() => setRefreshKey((k) => k + 1)} />
      ) : filtered.length === 0 ? (
        <EmptyState title="No reports yet" />
      ) : (
        <div className="overflow-hidden rounded-2xl border bg-card soft-shadow">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report #</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Sample</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Version</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pageItems.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell className="font-medium">
                      {report.reportNumber}
                    </TableCell>
                    <TableCell>{report.title}</TableCell>
                    <TableCell>{report.sampleNumber || "—"}</TableCell>
                    <TableCell>
                      <StatusBadge status={report.status} />
                    </TableCell>
                    <TableCell>v{report.version}</TableCell>
                    <TableCell>{formatDateTime(report.createdAt)}</TableCell>
                    <TableCell className="space-x-2 text-right">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => downloadReport(report)}
                      >
                        <FileText className="mr-1 size-3.5" />
                        PDF
                      </Button>
                      {hasPermission("approve") && report.status !== "approved" && (
                        <Button size="sm" onClick={() => approve(report)}>
                          Approve
                        </Button>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
          <div className="flex justify-between border-t px-4 py-3 text-sm">
            <span>
              Page {page}/{totalPages}
            </span>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                disabled={page <= 1}
                onClick={() => setPage(page - 1)}
              >
                Previous
              </Button>
              <Button
                size="sm"
                variant="outline"
                disabled={page >= totalPages}
                onClick={() => setPage(page + 1)}
              >
                Next
              </Button>
            </div>
          </div>
        </div>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Generate Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Report Type</Label>
              <Select
                value={reportType}
                onValueChange={(v) => setReportType(v as Report["type"])}
              >
                <SelectTrigger className="rounded-xl">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="coa">Certificate of Analysis</SelectItem>
                  <SelectItem value="test_report">Test Report</SelectItem>
                  <SelectItem value="dashboard">Dashboard Report</SelectItem>
                  <SelectItem value="monthly">Monthly Report</SelectItem>
                  <SelectItem value="analyst">Analyst Report</SelectItem>
                  <SelectItem value="qa">QA Report</SelectItem>
                  <SelectItem value="laboratory">Laboratory Report</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Sample</Label>
              <Select value={sampleId} onValueChange={setSampleId}>
                <SelectTrigger className="rounded-xl">
                  <SelectValue placeholder="Optional sample" />
                </SelectTrigger>
                <SelectContent>
                  {samples.map((s) => (
                    <SelectItem key={s.id} value={s.id}>
                      {s.sampleNumber}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Test</Label>
              <Select value={testId} onValueChange={setTestId}>
                <SelectTrigger className="rounded-xl">
                  <SelectValue placeholder="Optional test" />
                </SelectTrigger>
                <SelectContent>
                  {tests.map((t) => (
                    <SelectItem key={t.id} value={t.id}>
                      {t.testNumber} · {t.testName}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button onClick={generate} disabled={saving}>
              {saving ? "Generating..." : "Generate"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </PageShell>
  );
}
