"use client";

import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Download, Eye, FileText, Plus, Search } from "lucide-react";
import { useAuth } from "@/contexts/auth-context";
import { COLLECTIONS, PAGE_SIZE } from "@/lib/constants";
import {
  createDocument,
  getNextSequence,
  logActivity,
  logAudit,
  updateDocument,
} from "@/lib/firebase/firestore";
import {
  notifyReportApprovalRequired,
  notifyReportApproved,
} from "@/lib/notifications";
import { exportToCsv, exportToExcel, exportToPdf } from "@/lib/export";
import { formatDateTime } from "@/lib/utils";
import {
  useCollection,
  useDebouncedValue,
  usePagination,
} from "@/hooks/use-firestore";
import { useSearchQueryParam } from "@/hooks/use-search-query";
import { PageHeader } from "@/components/shared/page-header";
import {
  EmptyState,
  ErrorState,
  PageShell,
  TableSkeleton,
} from "@/components/shared/states";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { ApprovalStatus, LabTest, Report, Sample } from "@/types";

const REPORT_FETCH_LIMIT = 5000;

const REPORT_TITLES: Record<Report["type"], string> = {
  coa: "Certificate of Analysis",
  test_report: "Test Report",
  dashboard: "Dashboard Report",
  monthly: "Monthly Report",
  analyst: "Analyst Report",
  qa: "QA Report",
  laboratory: "Laboratory Report",
};

const APPROVABLE_STATUSES: ApprovalStatus[] = ["pending", "in_review"];

function buildReportContent({
  reportType,
  sample,
  test,
  generatedBy,
}: {
  reportType: Report["type"];
  sample?: Sample;
  test?: LabTest;
  generatedBy?: string;
}) {
  return [
    REPORT_TITLES[reportType],
    sample ? `Sample: ${sample.sampleNumber}` : "",
    sample?.productName ? `Product: ${sample.productName}` : "",
    sample?.batchNumber ? `Batch: ${sample.batchNumber}` : "",
    test ? `Test: ${test.testNumber} (${test.testName})` : "",
    test ? `Analyst: ${test.analystName || "—"}` : "",
    `Generated by: ${generatedBy || "—"}`,
    `Date: ${new Date().toLocaleString("en-IN")}`,
    test ? `Result: ${test.resultStatus} | Workflow: ${test.status}` : "",
    test?.parameters?.length
      ? [
          "",
          "Parameters:",
          ...test.parameters.map(
            (param) =>
              `- ${param.name}: ${param.observedValue ?? "—"} ${param.unit || ""} (${param.resultStatus})`
          ),
        ].join("\n")
      : "",
  ]
    .filter(Boolean)
    .join("\n");
}

function validateReportInput(
  reportType: Report["type"],
  sampleId: string,
  testId: string
) {
  if (reportType === "coa") {
    if (!sampleId || !testId) {
      return "COA requires both a sample and an approved test";
    }
  }
  if (reportType === "test_report" && !testId) {
    return "Test report requires a linked test";
  }
  return null;
}

export default function ReportsPage() {
  const { profile, hasPermission } = useAuth();
  const [refreshKey, setRefreshKey] = useState(0);
  const { data, loading, error } = useCollection<Report>(
    COLLECTIONS.reports,
    refreshKey,
    REPORT_FETCH_LIMIT
  );
  const { data: samples } = useCollection<Sample>(COLLECTIONS.samples);
  const { data: tests } = useCollection<LabTest>(COLLECTIONS.tests);
  const [search, setSearch] = useState("");
  useSearchQueryParam(setSearch);
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const debounced = useDebouncedValue(search);
  const [open, setOpen] = useState(false);
  const [detail, setDetail] = useState<Report | null>(null);
  const [reportType, setReportType] = useState<Report["type"]>("coa");
  const [sampleId, setSampleId] = useState("");
  const [testId, setTestId] = useState("");
  const [saving, setSaving] = useState(false);

  const activeReports = useMemo(
    () => data.filter((report) => report.isActive !== false),
    [data]
  );

  const activeSamples = useMemo(
    () => samples.filter((sample) => sample.isActive !== false),
    [samples]
  );

  const eligibleTests = useMemo(() => {
    let list = tests.filter((test) => test.isActive !== false);
    if (sampleId) {
      list = list.filter((test) => test.sampleId === sampleId);
    }
    if (["coa", "test_report"].includes(reportType)) {
      list = list.filter((test) => ["approved", "released"].includes(test.status));
    }
    return list;
  }, [tests, sampleId, reportType]);

  const filtered = useMemo(() => {
    const q = debounced.trim().toLowerCase();
    return activeReports.filter((report) => {
      const matchesType = typeFilter === "all" || report.type === typeFilter;
      const matchesStatus = statusFilter === "all" || report.status === statusFilter;
      const matchesSearch =
        !q ||
        report.reportNumber.toLowerCase().includes(q) ||
        report.title.toLowerCase().includes(q) ||
        (report.sampleNumber || "").toLowerCase().includes(q) ||
        (report.generatedByName || "").toLowerCase().includes(q);
      return matchesType && matchesStatus && matchesSearch;
    });
  }, [activeReports, debounced, typeFilter, statusFilter]);

  const { page, setPage, totalPages, pageItems, total } = usePagination(
    filtered,
    PAGE_SIZE
  );

  const canGenerate = hasPermission("viewReports") || hasPermission("export");
  const canApprove = hasPermission("approve");

  const generate = async () => {
    const validationError = validateReportInput(reportType, sampleId, testId);
    if (validationError) {
      toast.error(validationError);
      return;
    }

    setSaving(true);
    try {
      const sample = activeSamples.find((item) => item.id === sampleId);
      const test = eligibleTests.find((item) => item.id === testId);
      if (reportType === "coa" && (!sample || !test)) {
        throw new Error("Select a valid sample and approved test for COA");
      }
      if (reportType === "test_report" && !test) {
        throw new Error("Select a valid approved test");
      }

      let reportNumber = `RPT-${Date.now()}`;
      try {
        reportNumber = await getNextSequence("reports", "RPT");
      } catch {
        // fallback local generator if counters unavailable
      }

      const content = buildReportContent({
        reportType,
        sample,
        test,
        generatedBy: profile?.displayName,
      });

      const id = await createDocument(COLLECTIONS.reports, {
        reportNumber,
        type: reportType,
        sampleId: sample?.id,
        sampleNumber: sample?.sampleNumber,
        testId: test?.id,
        title: REPORT_TITLES[reportType],
        status: "pending",
        version: 1,
        content,
        generatedBy: profile?.uid,
        generatedByName: profile?.displayName,
      });

      await logActivity({
        action: "Generate Report",
        entityType: "reports",
        entityId: id,
        entityLabel: reportNumber,
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        userEmail: profile?.email,
      });
      await logAudit({
        entityType: "reports",
        entityId: id,
        entityLabel: reportNumber,
        field: "record",
        oldValue: "",
        newValue: "generated",
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        action: "create",
      });
      await notifyReportApprovalRequired(reportNumber);
      toast.success("Report generated");
      setOpen(false);
      setSampleId("");
      setTestId("");
      setRefreshKey((k) => k + 1);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to generate");
    } finally {
      setSaving(false);
    }
  };

  const approve = async (report: Report) => {
    if (!APPROVABLE_STATUSES.includes(report.status)) {
      toast.error("Only pending or in-review reports can be approved");
      return;
    }
    setSaving(true);
    try {
      await updateDocument(COLLECTIONS.reports, report.id, {
        status: "approved",
        approvedBy: profile?.uid,
        approvedByName: profile?.displayName,
        version: (report.version || 1) + 1,
        updatedBy: profile?.uid,
      });
      await logActivity({
        action: "Approve Report",
        entityType: "reports",
        entityId: report.id,
        entityLabel: report.reportNumber,
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        userEmail: profile?.email,
      });
      await logAudit({
        entityType: "reports",
        entityId: report.id,
        entityLabel: report.reportNumber,
        field: "status",
        oldValue: report.status,
        newValue: "approved",
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        action: "approve",
      });
      if (report.generatedBy) {
        await notifyReportApproved(report.generatedBy, report.reportNumber);
      }
      toast.success("Report approved");
      setRefreshKey((k) => k + 1);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Approval failed");
    } finally {
      setSaving(false);
    }
  };

  const reject = async (report: Report) => {
    if (!APPROVABLE_STATUSES.includes(report.status)) {
      toast.error("Only pending or in-review reports can be rejected");
      return;
    }
    setSaving(true);
    try {
      await updateDocument(COLLECTIONS.reports, report.id, {
        status: "rejected",
        updatedBy: profile?.uid,
      });
      await logActivity({
        action: "Reject Report",
        entityType: "reports",
        entityId: report.id,
        entityLabel: report.reportNumber,
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        userEmail: profile?.email,
      });
      await logAudit({
        entityType: "reports",
        entityId: report.id,
        entityLabel: report.reportNumber,
        field: "status",
        oldValue: report.status,
        newValue: "rejected",
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        action: "reject",
      });
      toast.success("Report rejected");
      setRefreshKey((k) => k + 1);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Rejection failed");
    } finally {
      setSaving(false);
    }
  };

  const downloadReport = async (report: Report) => {
    exportToPdf(
      report.title,
      [
        {
          reportNumber: report.reportNumber,
          sample: report.sampleNumber || "",
          status: report.status,
          version: report.version,
          generatedBy: report.generatedByName || "",
          approvedBy: report.approvedByName || "",
          content: report.content || "",
        },
      ],
      [
        { key: "reportNumber", label: "Report #" },
        { key: "sample", label: "Sample" },
        { key: "status", label: "Status" },
        { key: "version", label: "Version" },
        { key: "generatedBy", label: "Generated By" },
        { key: "approvedBy", label: "Approved By" },
        { key: "content", label: "Content" },
      ],
      report.reportNumber
    );
    try {
      await logActivity({
        action: "Download Report",
        entityType: "reports",
        entityId: report.id,
        entityLabel: report.reportNumber,
        userId: profile?.uid || "",
        userName: profile?.displayName || "User",
        userEmail: profile?.email,
      });
    } catch {
      // Download should not fail if activity logging fails.
    }
  };

  const exportRows = filtered.map((report) => ({
    reportNumber: report.reportNumber,
    title: report.title,
    type: report.type,
    sample: report.sampleNumber || "",
    status: report.status,
    version: report.version,
    generatedBy: report.generatedByName || "",
  }));
  const cols = [
    { key: "reportNumber", label: "Report #" },
    { key: "title", label: "Title" },
    { key: "type", label: "Type" },
    { key: "sample", label: "Sample" },
    { key: "status", label: "Status" },
    { key: "version", label: "Version" },
    { key: "generatedBy", label: "Generated By" },
  ];

  return (
    <PageShell>
      <PageHeader
        title="Reports"
        description="Generate COA, test reports, and operational exports."
        breadcrumbs={[
          { label: "Dashboard", href: "/dashboard" },
          { label: "Reports" },
        ]}
        actions={
          <>
            {hasPermission("export") && (
              <>
                <Button
                  variant="outline"
                  className="h-10 rounded-xl"
                  onClick={() => exportToExcel("reports", exportRows, cols)}
                >
                  <Download className="mr-2 size-4" />
                  Excel
                </Button>
                <Button
                  variant="outline"
                  className="h-10 rounded-xl"
                  onClick={() => exportToCsv("reports", exportRows, cols)}
                >
                  CSV
                </Button>
              </>
            )}
            {canGenerate && (
              <Button className="h-10 rounded-xl" onClick={() => setOpen(true)}>
                <Plus className="mr-2 size-4" />
                Generate Report
              </Button>
            )}
          </>
        }
      />

      <div className="mb-4 grid gap-3 md:grid-cols-3">
        <div className="relative md:col-span-1">
          <Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-10 rounded-xl pl-9"
            placeholder="Search report #, title, sample..."
          />
        </div>
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="h-10 rounded-xl">
            <SelectValue placeholder="Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All types</SelectItem>
            {Object.entries(REPORT_TITLES).map(([value, label]) => (
              <SelectItem key={value} value={value}>
                {label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="h-10 rounded-xl">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses</SelectItem>
            {(
              ["pending", "in_review", "approved", "rejected", "released"] as ApprovalStatus[]
            ).map((status) => (
              <SelectItem key={status} value={status}>
                {status.replace(/_/g, " ")}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {activeReports.length >= REPORT_FETCH_LIMIT && (
        <p className="mb-4 text-sm text-muted-foreground">
          Showing the latest {REPORT_FETCH_LIMIT.toLocaleString()} reports. Older
          records may not appear in this list.
        </p>
      )}

      {loading ? (
        <TableSkeleton />
      ) : error ? (
        <ErrorState description={error} onRetry={() => setRefreshKey((k) => k + 1)} />
      ) : filtered.length === 0 ? (
        <EmptyState
          title="No reports yet"
          action={
            canGenerate ? (
              <Button onClick={() => setOpen(true)}>
                <Plus className="mr-2 size-4" />
                Generate Report
              </Button>
            ) : undefined
          }
        />
      ) : (
        <div className="overflow-hidden rounded-2xl border bg-card soft-shadow">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report #</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Sample</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Version</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pageItems.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell className="font-medium">
                      {report.reportNumber}
                    </TableCell>
                    <TableCell>{report.title}</TableCell>
                    <TableCell className="capitalize">
                      {report.type.replace(/_/g, " ")}
                    </TableCell>
                    <TableCell>{report.sampleNumber || "—"}</TableCell>
                    <TableCell>
                      <StatusBadge status={report.status} />
                    </TableCell>
                    <TableCell>v{report.version}</TableCell>
                    <TableCell>{formatDateTime(report.createdAt)}</TableCell>
                    <TableCell className="text-right">
                      <div className="flex flex-wrap justify-end gap-2">
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => setDetail(report)}
                        >
                          <Eye className="mr-1 size-3.5" />
                          View
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => downloadReport(report)}
                        >
                          <FileText className="mr-1 size-3.5" />
                          PDF
                        </Button>
                        {canApprove && APPROVABLE_STATUSES.includes(report.status) && (
                          <>
                            <Button
                              size="sm"
                              disabled={saving}
                              onClick={() => approve(report)}
                            >
                              Approve
                            </Button>
                            <Button
                              size="sm"
                              variant="destructive"
                              disabled={saving}
                              onClick={() => reject(report)}
                            >
                              Reject
                            </Button>
                          </>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
          <div className="flex justify-between border-t px-4 py-3 text-sm">
            <span className="text-muted-foreground">
              {total} reports · Page {page}/{totalPages}
            </span>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                disabled={page <= 1}
                onClick={() => setPage(page - 1)}
              >
                Previous
              </Button>
              <Button
                size="sm"
                variant="outline"
                disabled={page >= totalPages}
                onClick={() => setPage(page + 1)}
              >
                Next
              </Button>
            </div>
          </div>
        </div>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Generate Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Report Type</Label>
              <Select
                value={reportType}
                onValueChange={(value) => {
                  setReportType(value as Report["type"]);
                  setTestId("");
                }}
              >
                <SelectTrigger className="rounded-xl">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(REPORT_TITLES).map(([value, label]) => (
                    <SelectItem key={value} value={value}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>
                Sample {["coa"].includes(reportType) ? "*" : "(optional)"}
              </Label>
              <Select
                value={sampleId}
                onValueChange={(value) => {
                  setSampleId(value);
                  setTestId("");
                }}
              >
                <SelectTrigger className="rounded-xl">
                  <SelectValue placeholder="Select sample" />
                </SelectTrigger>
                <SelectContent>
                  {activeSamples.map((sample) => (
                    <SelectItem key={sample.id} value={sample.id}>
                      {sample.sampleNumber}
                      {sample.productName ? ` · ${sample.productName}` : ""}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>
                Test {["coa", "test_report"].includes(reportType) ? "*" : "(optional)"}
              </Label>
              <Select value={testId} onValueChange={setTestId}>
                <SelectTrigger className="rounded-xl">
                  <SelectValue placeholder="Select test" />
                </SelectTrigger>
                <SelectContent>
                  {eligibleTests.length === 0 ? (
                    <SelectItem value="__none" disabled>
                      No eligible tests
                    </SelectItem>
                  ) : (
                    eligibleTests.map((test) => (
                      <SelectItem key={test.id} value={test.id}>
                        {test.testNumber} · {test.testName}
                      </SelectItem>
                    ))
                  )}
                </SelectContent>
              </Select>
            </div>
            {["coa", "test_report"].includes(reportType) && (
              <p className="text-xs text-muted-foreground">
                COA and test reports require approved or released tests.
              </p>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button onClick={generate} disabled={saving}>
              {saving ? "Generating..." : "Generate"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!detail} onOpenChange={(openState) => !openState && setDetail(null)}>
        <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>{detail?.reportNumber}</DialogTitle>
          </DialogHeader>
          {detail && (
            <div className="space-y-4 text-sm">
              <div className="flex flex-wrap gap-2">
                <StatusBadge status={detail.status} />
                <StatusBadge status={detail.type} label={detail.title} />
              </div>
              <div className="grid gap-2 md:grid-cols-2">
                <p>
                  <span className="text-muted-foreground">Sample:</span>{" "}
                  {detail.sampleNumber || "—"}
                </p>
                <p>
                  <span className="text-muted-foreground">Version:</span> v
                  {detail.version}
                </p>
                <p>
                  <span className="text-muted-foreground">Generated by:</span>{" "}
                  {detail.generatedByName || "—"}
                </p>
                <p>
                  <span className="text-muted-foreground">Generated at:</span>{" "}
                  {formatDateTime(detail.createdAt)}
                </p>
                <p>
                  <span className="text-muted-foreground">Approved by:</span>{" "}
                  {detail.approvedByName || "—"}
                </p>
              </div>
              <div className="rounded-xl border bg-muted/20 p-4">
                <p className="mb-2 font-medium">Report Content</p>
                <pre className="whitespace-pre-wrap text-xs leading-relaxed">
                  {detail.content || "No content available."}
                </pre>
              </div>
              <DialogFooter className="px-0">
                <Button variant="outline" onClick={() => downloadReport(detail)}>
                  <FileText className="mr-2 size-4" />
                  Download PDF
                </Button>
              </DialogFooter>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </PageShell>
  );
}
